### ISSUE TITLE
Fix the spamming log message "ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path" on masters

### ISSUE THREAD

**Issue by mbarbero** [eclipse-cbi/jiro#11]
It seems to be an [issue](https://issues.jenkins-ci.org/browse/JENKINS-53131) with the OkHttp lib. See 

Jetty describe a [solution](https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html#alpn-openjdk8): add alpn to bootclasspath `java -Xbootclasspath/p:libs/alpn-boot-8.1.9.v20160720.jar`

List of matching versions are here https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html#alpn-versions and binaries can be downloaded on maven central https://search.maven.org/search?q=g:org.mortbay.jetty.alpn%20a:alpn-boot

This won't be necessary anymore as soon as Jenkins will run on OpenJDK9+

**Comment by encryptblockr** [comment]
> i believe this is similar issue but this is using current latest lts image
> so shouldn't be a permanent fix even in lts version?


I am getting the following error trying to integrate jenkins server to kubernetes cluster so that jenkins agents are spun on on the kubernetes cluster to run jobs

```
2020-02-06 17:21:26.875+0000 [id=961]	WARNING	o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: kubernetes-1f2n5, template=PodTemplate{inheritFrom='', name='kubernetes', namespace='', label='kubernetes', serviceAccount='default', nodeSelector='', nodeUsageMode=EXCLUSIVE, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], volumes=[HostPathVolume [mountPath=/var/run/docker.sock, hostPath=/var/run/docker.sock]], containers=[ContainerTemplate{name='jnlp', image='joao29a/jnlp-slave-alpine-docker', workingDir='/home/jenkins/', command='', args='', ttyEnabled=true, resourceRequestCpu='', resourceRequestMemory='', resourceLimitCpu='', resourceLimitMemory='', envVars=[KeyValueEnvVar [getValue()=http://x.x.x.x:8080, getKey()=JENKINS_URL]], livenessProbe=org.csanchez.jenkins.plugins.kubernetes.ContainerLivenessProbe@de43a86}]}
io.fabric8.kubernetes.client.KubernetesClientException:
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:198)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-02-06 17:21:26.876+0000 [id=961]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent kubernetes-1f2n5
2020-02-06 17:21:26.890+0000 [id=961]	INFO	o.c.j.p.k.KubernetesSlave#deleteSlavePod: Terminated Kubernetes instance for agent test/kubernetes-1f2n5
2020-02-06 17:21:26.890+0000 [id=961]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Disconnected computer kubernetes-1f2n5
Terminated Kubernetes instance for agent test/kubernetes-1f2n5
Disconnected computer kubernetes-1f2n5
2020-02-06 17:21:36.747+0000 [id=31]	INFO	o.c.j.p.k.KubernetesCloud#provision: Excess workload after pending Kubernetes agents: 1
2020-02-06 17:21:36.747+0000 [id=31]	INFO	o.c.j.p.k.KubernetesCloud#provision: Template for label kubernetes: Kubernetes Pod Template
2020-02-06 17:21:36.756+0000 [id=31]	INFO	h.s.NodeProvisioner$StandardStrategyImpl#apply: Started provisioning Kubernetes Pod Template from kubernetes with 1 executors. Remaining excess workload: 0
2020-02-06 17:21:46.798+0000 [id=961]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Created Pod: test/kubernetes-9sp9x
2020-02-06 17:21:46.815+0000 [id=30]	INFO	hudson.slaves.NodeProvisioner#lambda$update$6: Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)
2020-02-06 17:21:46.860+0000 [id=968]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-02-06 17:21:46.863+0000 [id=968]	WARNING	i.f.k.c.d.i.WatchConnectionManager$1#onFailure: Exec Failure: HTTP 403, Status: 403 -
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-02-06 17:21:46.864+0000 [id=961]	WARNING	o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: kubernetes-9sp9x, template=PodTemplate{inheritFrom='', name='kubernetes', namespace='', label='kubernetes', serviceAccount='default', nodeSelector='', nodeUsageMode=EXCLUSIVE, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], volumes=[HostPathVolume [mountPath=/var/run/docker.sock, hostPath=/var/run/docker.sock]], containers=[ContainerTemplate{name='jnlp', image='joao29a/jnlp-slave-alpine-docker', workingDir='/home/jenkins/', command='', args='', ttyEnabled=true, resourceRequestCpu='', resourceRequestMemory='', resourceLimitCpu='', resourceLimitMemory='', envVars=[KeyValueEnvVar [getValue()=http://x.x.x.x:8080, getKey()=JENKINS_URL]], livenessProbe=org.csanchez.jenkins.plugins.kubernetes.ContainerLivenessProbe@de43a86}]}
io.fabric8.kubernetes.client.KubernetesClientException:
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:198)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-02-06 17:21:46.865+0000 [id=961]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent kubernetes-9sp9x
2020-02-06 17:21:46.899+0000 [id=961]	INFO	o.c.j.p.k.KubernetesSlave#deleteSlavePod: Terminated Kubernetes instance for agent test/kubernetes-9sp9x
Terminated Kubernetes instance for agent test/kubernetes-9sp9x
2020-02-06 17:21:46.900+0000 [id=961]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Disconnected computer kubernetes-9sp9x
Disconnected computer kubernetes-9sp9x
```

**Comment by mbarbero** [comment]
I don't see that anymore with more recent builds of openjdk 8 from AdoptOpenJDK

**Comment by medianick** [comment]
@mbarbero what is the version number of the more recent build of OpenJDK 8 where you don't see this anymore? I'm still seeing it with 1.8.0_242.

**Comment by mbarbero** [comment]
You're right, I'm still seeing this as well. Must have looked at it too quickly. Thanks for the heads up.

**Comment by medianick** [comment]
I actually just upgraded to 1.8.0_252 and the messages seem to have gone away.

**Comment by fredg02** [comment]
I haven't seen those messages in a long time. Therefore closing.
